### PR TITLE
Implementation of handlers for NonfungiblePositionManager

### PR DESCRIPTION
**Pull request by benesjan**
Hello,

I thought it would be useful to have a position entity similar to the LiquidityPosition from Uni v2 subgraph. This implementation is solely relying on the NonfungiblePositionManager handlers. I am a bit worried that people will eventually use Pools directly instead of through the Manager due to co-developing services to Uni (strategies etc.). However I think it makes sense to eventually update the code if needed instead of complicating our lives right now by not using the more comprehensive events of the NonfungiblePositionManager.

I am open to any feedback.

Best regards,
Jan

### CODE REVIEW

**Comment by ianlapham** [comment]
@benesjan Amazing will review this today - would be good to get merged and have a subgraph start syncing

**Review by ianlapham — APPROVED** [review]
Great work here - the logic here looks solid and was generally how I was thinking of approaching it. 

Happy to merge this and try to test with some real data. 

One note - it may be a nice to have to compute things like ROI at points where they withdraw from their position - but this is non trivial and may need more research to do correctly 

basically - how can we tell how well this position is performing? Is there a way to track fees without relying on collect events only? This might not be realistic as we may need to update every single Position on every swap - thatd be to expensive.

**Comment by benesjan** [comment]
> Great work here - the logic here looks solid and was generally how I was thinking of approaching it.
> 
> Happy to merge this and try to test with some real data.
> 
> One note - it may be a nice to have to compute things like ROI at points where they withdraw from their position - but this is non trivial and may need more research to do correctly
> 
> basically - how can we tell how well this position is performing? Is there a way to track fees without relying on collect events only? This might not be realistic as we may need to update every single Position on every swap - thatd be to expensive. But, are there data points we should be storing that would help calculate things like this in some other process that uses this data.
> 
> All unanswered for now but just ideas.

Thank you :blush:,
to address your note, I am currently working exactly on that on [this branch](https://github.com/croco-finance/uniswap-v3-subgraph/commits/feat/fee-related-vars) as it's something we badly need for croco.  Unfortunately the code will probably be pretty ugly given that it's necessary to track many vars which are not exposed through events for the fee computation to be possible.

Once I get it working and test it I will send a PR :relieved:

**Comment by ianlapham** [comment]
@benesjan I merged this and started a deploy but looks like it failed - classic graph not giving me error logs so trying to manually debug - do you have telegram or some channel to chat?

**Pull request merged**
